# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"
    # config.vbguest.installer_options = { allow_kernel_upgrade: true }

    config.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
    end

    config.vm.provider :libvirt do |libvirt|
        libvirt.driver = "qemu"
        libvirt.qemu_use_session = false
        libvirt.memory = 1024
    end

    config.vm.define "pmm" do |pmm|
        pmm.vm.hostname = "pmm-server"
        pmm.vm.provision "shell", path: "provision-pmm-server.sh"
        pmm.vm.network "private_network", ip: "192.168.200.25"
        pmm.vm.network :forwarded_port, guest: 443, host: 9995

        pmm.vm.provider "virtualbox" do |vb|
            vb.memory = "2048"
        end

        pmm.vm.provider :libvirt do |libvirt|
            libvirt.memory = 2048
        end
    end
                                                                                                                          
    config.vm.define "node1" do |node1|
        node1.vm.hostname = "node1"
        node1.vm.network "private_network", ip: "192.168.200.20"
        node1.vm.provision "shell", path: "provision-pxc.sh"
    end
                                                                                                                          
    config.vm.define "node2" do |node2|
        node2.vm.hostname = "node2"
        node2.vm.network "private_network", ip: "192.168.200.21"
        node2.vm.provision "shell", path: "provision-pxc.sh"
    end

    config.vm.define "node3" do |node3|
        node3.vm.hostname = "node3"
        node3.vm.network "private_network", ip: "192.168.200.22"
        node3.vm.provision "shell", path: "provision-pxc.sh"
    end

  end                                                                                                                     
  